name-template: '$RESOLVED_VERSION'

tag-template: '$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/stephenkelzer/stephenkelzer/compare/$PREVIOUS_TAG...$RESOLVED_VERSION