name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:

  build-and-test:

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:

      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Download WASM Target
        run: rustup target add wasm32-unknown-unknown
           
      - uses: actions/checkout@v3

      - name: Lint
        run: cargo check

      - name: Build
        run: trunk build --release
        
      - name: Run tests
        run: cargo test --verbose